export const USER_REPOSITORY = 'USER_REPOSITORY';
export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';
export const COOKBOOK_REPOSITORY = 'COOKBOOK_REPOSITORY';
export const RECIPE_REPOSITORY = 'RECIPE_REPOSITORY';
export const LIKE_REPOSITORY = 'LIKE_REPOSITORY';
